import type { Locale } from "@/i18n/locales";

type LocalizedText = Record<Locale, string>;

export type RadioTenantOrRegion = "menton" | "loire";

export type RadioStation = {
  id: string;
  tenant: RadioTenantOrRegion;
  name: LocalizedText;
  image?: string;
  audioStreamUrl?: string;
  fmFrequency?: string;
  languages?: string[];
  contentTypes?: string[];
  musicStyles?: string[];
  onlineStreamUrl?: string;
  websiteUrl?: string;
  shortLabel?: LocalizedText;
  notes?: LocalizedText;
  usefulFor?: string[];
};

export const radioStations: RadioStation[] = [
  {
    id: "france-bleu-cote-azur",
    image: "/images/guide/ici-azur-france-bleu-azur.png",
    tenant: "menton",
    name: {
      en: "France Bleu Côte d'Azur",
      fr: "France Bleu Côte d'Azur",
      it: "France Bleu Côte d'Azur",
      uk: "France Bleu Côte d'Azur",
    },
    contentTypes: ["local news", "current affairs", "music"],
    languages: ["French"],
    audioStreamUrl: "https://stream.radiofrance.fr/fbazur/fbazur.m3u8?id=radiofrance",
    onlineStreamUrl: "https://www.francebleu.fr/",
    websiteUrl: "https://www.francebleu.fr/",
    shortLabel: {
      en: "Useful for local weather, road and event updates",
      fr: "Infos pratiques locales: météo, routes, agenda",
      it: "Per aggiornamenti locali: meteo, traffico, eventi",
      uk: "Місцеві новини: погода, дороги, події",
    },
    notes: {
      en: "Official regional public-service station with broad Riviera coverage and practical updates.",
      fr: "Station public-service régionale avec couverture Rivière large et informations pratiques.",
      it: "Radio pubblica regionale con ampia copertura rivierasco e aggiornamenti pratici.",
      uk: "Публічна регіональна радіостанція з широким покриттям Рив’єри й практичними оновленнями.",
    },
    usefulFor: ["practical planning", "travel", "commute"],
  },
  {
    id: "rmc-azur",
    image: "/images/guide/rmc.png",
    tenant: "menton",
    name: {
      en: "RMC",
      fr: "RMC",
      it: "RMC",
      uk: "RMC",
    },
    contentTypes: ["news", "lifestyle", "music"],
    languages: ["French"],
    audioStreamUrl: "https://audio.bfmtv.com/rmcradio_128.mp3",
    onlineStreamUrl: "https://www.rmc.fr/stream",
    websiteUrl: "https://www.rmc.fr/",
    shortLabel: {
      en: "General news, sports and travel-safe updates",
      fr: "Actualités générales, sports et mises à jour utiles",
      it: "Notizie, sport e aggiornamenti pratici",
      uk: "Новини, спорт і корисні поінформування",
    },
    notes: {
      en: "Useful for trip timing and general headlines alongside dedicated local sources.",
      fr: "Pratique pour la gestion des horaires de voyage, en complément des sources locales.",
      it: "Utile per orari e aggiornamenti di viaggio, insieme alle fonti locali dedicate.",
      uk: "Корисна для орієнтації за подіями та новинами, поряд із локальними джерелами.",
    },
    usefulFor: ["trip headlines", "trip prep"],
  },
  {
    id: "radio-classique-loire",
    image: "/images/guide/radio-classique.png",
    tenant: "loire",
    name: {
      en: "Radio Classique",
      fr: "Radio Classique",
      it: "Radio Classique",
      uk: "Radio Classique",
    },
    contentTypes: ["classical music"],
    languages: ["French"],
    musicStyles: ["classical", "jazz"],
    websiteUrl: "https://www.radioclassique.fr/",
    shortLabel: {
      en: "Classical and jazz for quieter evening plans",
      fr: "Classique et jazz pour des soirées douces",
      it: "Classica e jazz per serate più tranquille",
      uk: "Класика й джаз для спокійних вечорів",
    },
    notes: {
      en: "Not transport-critical; useful when planning evening breaks and downtime in Menton.",
      fr: "Non critique pour les transports; utile pour préparer des soirées plus calmes.",
      it: "Non prioritario per il trasporto; utile per pianificare serate tranquille.",
      uk: "Не критична для транспорту, корисна для планування спокійних вечорів.",
    },
    usefulFor: ["evening downtime", "weekend planning"],
  },
  {
    id: "monaco-mondiale-radio",
    image: "/images/guide/radio-monaco.png",
    tenant: "menton",
    name: {
      en: "Monaco Info Radio",
      fr: "Monaco Info Radio",
      it: "Monaco Info Radio",
      uk: "Monaco Info Radio",
    },
    contentTypes: ["city updates", "events", "traffic"],
    languages: ["French", "English"],
    websiteUrl: "https://www.mairie.mc/",
    shortLabel: {
      en: "Crossing toward Monaco? Useful for city-level updates.",
      fr: "Vers Monaco: infos officielles utiles.",
      it: "Per Monaco: informazioni utili sul territorio cittadino.",
      uk: "Для подорожей до Монако: актуальні відомості по місту.",
    },
    usefulFor: ["day trips", "family visits", "event timing"],
  },
  {
    id: "radio-vinci-autoroutes-1077",
    image: "/images/guide/radio-vinci-autoroutes.png",
    tenant: "menton",
    name: {
      en: "Radio VINCI Autoroutes",
      fr: "Radio VINCI Autoroutes",
      it: "Radio VINCI Autoroutes",
      uk: "Radio VINCI Autoroutes",
    },
    fmFrequency: "107.7 MHz",
    contentTypes: ["traffic", "road info", "weather", "news"],
    languages: ["French"],
    musicStyles: [],
    audioStreamUrl: "https://sc.creacast.com/rva-cofiroute-1",
    websiteUrl: "https://www.radio-vinci-autoroutes.fr/",
    onlineStreamUrl: "https://www.radio-vinci-autoroutes.fr/ecouter/",
    shortLabel: {
      en: "Traffic, road safety and weather for motorway routing.",
      fr: "Trafic, sécurité routière et météo pour les trajets.",
      it: "Traffico, sicurezza stradale e meteo per gli spostamenti.",
      uk: "Трафік, дорожня безпека та погода для автомагістралей.",
    },
    notes: {
      en: "Useful when crossing toward Nice, Cannes, Monaco or the Italian border by car.",
      fr: "Utile pour aller vers Nice, Cannes, Monaco ou la frontière italienne.",
      it: "Utile per andare verso Nizza, Cannes, Monaco o verso il confine italiano.",
      uk: "Корисна перед виїздом до Ніцца, Канн, Монако або на італійський кордон.",
    },
    usefulFor: ["travel", "traffic", "driving", "airport"],
  },
  {
    id: "ici-azur-france-bleu-azur",
    image: "/images/guide/ici-azur-france-bleu-azur.png",
    tenant: "menton",
    name: {
      en: "Ici Azur / France Bleu Azur",
      fr: "Ici Azur / France Bleu Azur",
      it: "Ici Azur / France Bleu Azur",
      uk: "Ici Azur / France Bleu Azur",
    },
    fmFrequency: "94.8 MHz",
    contentTypes: ["local news", "weather", "practical updates"],
    languages: ["French"],
    audioStreamUrl: "https://stream.radiofrance.fr/fbazur/fbazur.m3u8?id=radiofrance",
    websiteUrl: "https://www.francebleu.fr/",
    onlineStreamUrl: "https://www.francebleu.fr/",
    shortLabel: {
      en: "Regional Riviera news and practical local updates.",
      fr: "Informations régionales et conseils pratiques.",
      it: "Notizie regionali e aggiornamenti pratici.",
      uk: "Регіональні новини та практичні локальні оновлення.",
    },
    notes: {
      en: "One of the best practical French stations for Menton and nearby Côte d'Azur context.",
      fr: "L'une des stations francaises pratiques pour le contexte Menton / Côte d'Azur.",
      it: "Una delle migliori radio pratiche francesi per Menton e la Côte d'Azur.",
      uk: "Одна з практичніших французьких станцій для Ментона та Côte d'Azur.",
    },
    usefulFor: ["local-news", "weather", "family", "day trips"],
  },
  {
    id: "riviera-radio",
    image: "/images/guide/riviera-radio.png",
    tenant: "menton",
    name: {
      en: "Riviera Radio",
      fr: "Riviera Radio",
      it: "Riviera Radio",
      uk: "Riviera Radio",
    },
    fmFrequency: "106.5 MHz",
    contentTypes: ["traffic", "entertainment", "news", "lifestyle"],
    languages: ["English"],
    musicStyles: ["pop", "adult contemporary", "easy listening"],
    audioStreamUrl: "https://rivieraradio.ice.infomaniak.ch/stream",
    websiteUrl: "https://www.rivieraradio.mc/",
    onlineStreamUrl: "https://www.rivieraradio.mc/en/radio/player",
    shortLabel: {
      en: "English-language Riviera updates and music.",
      fr: "Actualités et musique en anglais pour la Riviera.",
      it: "Aggiornamenti in inglese e musica per la Riviera.",
      uk: "Англомовні новини Рив'єри та музика.",
    },
    notes: {
      en: "Practical for international visitors staying in Menton and moving toward Monaco or Nice.",
      fr: "Pratique pour les visiteurs internationaux à Menton ou vers Monaco et Nice.",
      it: "Utile per i visitatori internazionali a Menton con spostamenti verso Monaco o Nizza.",
      uk: "Практична для міжнародних гостей, які живуть у Ментоні та їдуть у Монако чи Ніцца.",
    },
    usefulFor: ["english-speaking guests", "day trips", "beach days"],
  },
  {
    id: "radio-monaco",
    image: "/images/guide/radio-monaco.png",
    tenant: "menton",
    name: {
      en: "Radio Monaco",
      fr: "Radio Monaco",
      it: "Radio Monaco",
      uk: "Radio Monaco",
    },
    fmFrequency: "95.4 MHz (Nice/Menton area), 98.2 MHz (Monaco)",
    contentTypes: ["music", "news", "entertainment"],
    languages: ["French"],
    musicStyles: ["electro-pop", "house", "chill-out", "jazz", "rock"],
    websiteUrl: "https://www.radiomonaco.org/",
    onlineStreamUrl: "https://www.radiomonaco.org/ecouter/",
    shortLabel: {
      en: "Monaco-focused station with music and local Riviera information.",
      fr: "Radio orientée Monaco avec musique et infos locales.",
      it: "Radio orientata su Monaco con musica e notizie locali.",
      uk: "Станція з акцентом на Монако, музикою та локальними новинами.",
    },
    notes: {
      en: "Useful when your trip includes Monaco evenings, short train rides and cross-border planning.",
      fr: "Utile si votre séjour inclut Monaco (soirées, train, planning transfrontalier).",
      it: "Utile se il tuo viaggio include Monaco: serate, treno e logica transfrontaliera.",
      uk: "Корисна, якщо подорож включає Монако: вечори, поїздка потягом, планування через кордон.",
    },
    usefulFor: ["monaco day trips", "evening drives", "nightlife"],
  },
  {
    id: "france-info",
    image: "/images/guide/france-info.png",
    tenant: "menton",
    name: {
      en: "France Info",
      fr: "France Info",
      it: "France Info",
      uk: "France Info",
    },
    fmFrequency: "105.5 MHz",
    contentTypes: ["news", "alerts", "national context"],
    languages: ["French"],
    audioStreamUrl: "https://icecast.radiofrance.fr/franceinfo-hifi.aac",
    websiteUrl: "https://www.francetvinfo.fr/",
    onlineStreamUrl: "https://www.radiofrance.fr/franceinfo",
    shortLabel: {
      en: "Continuous French news and major updates.",
      fr: "Info en continu sur l'actualité française et locale.",
      it: "Notizie continue su attualità e aggiornamenti francesi.",
      uk: "Безперервні французькі новини та важливі оновлення.",
    },
    notes: {
      en: "Best as a quick national context source before local checks.",
      fr: "Bonne source de contexte national avant les sources locales.",
      it: "Buona base di contesto nazionale prima di controllare le fonti locali.",
      uk: "Добре для загального контексту, потім перевіряйте локальні джерела.",
    },
    usefulFor: ["travel-disruptions", "news", "events"],
  },
  {
    id: "france-inter",
    image: "/images/guide/france-inter.png",
    tenant: "menton",
    name: {
      en: "France Inter",
      fr: "France Inter",
      it: "France Inter",
      uk: "France Inter",
    },
    fmFrequency: "97.0 MHz",
    contentTypes: ["talk", "culture", "news", "magazines"],
    languages: ["French"],
    audioStreamUrl: "https://stream.radiofrance.fr/monpetitfranceinter/monpetitfranceinter_hifi.m3u8",
    websiteUrl: "https://www.radiofrance.fr/franceinter",
    onlineStreamUrl: "https://www.radiofrance.fr/franceinter",
    shortLabel: {
      en: "French public radio with long-form interviews and debates.",
      fr: "Radio publique avec émissions longues, débats et culture.",
      it: "Radio pubblica con magazine, dibattiti e cultura.",
      uk: "Публічна радіо з довшими матеріалами, дискусіями та культурою.",
    },
    usefulFor: ["family", "culture", "french-practice"],
  },
  {
    id: "france-culture",
    image: "/images/guide/france-culture.png",
    tenant: "menton",
    name: {
      en: "France Culture",
      fr: "France Culture",
      it: "France Culture",
      uk: "France Culture",
    },
    fmFrequency: "89.6 MHz",
    contentTypes: ["culture", "documentary", "debate", "history"],
    languages: ["French"],
    audioStreamUrl: "https://icecast.radiofrance.fr/franceculture-hifi.aac",
    websiteUrl: "https://www.radiofrance.fr/franceculture",
    onlineStreamUrl: "https://www.radiofrance.fr/franceculture",
    shortLabel: {
      en: "Long-form cultural radio for slower evenings.",
      fr: "Culture en profondeur pour les soirées calmes.",
      it: "Radio culturale per serate più calme e lente.",
      uk: "Культурне радіо з довгими програмами для спокійних вечорів.",
    },
    usefulFor: ["quiet evenings", "culture", "learning"],
  },
  {
    id: "france-musique",
    image: "/images/guide/france-musique.png",
    tenant: "menton",
    name: {
      en: "France Musique",
      fr: "France Musique",
      it: "France Musique",
      uk: "France Musique",
    },
    fmFrequency: "91.7 MHz",
    contentTypes: ["music", "classical", "jazz", "concerts"],
    languages: ["French"],
    musicStyles: ["classical", "jazz"],
    audioStreamUrl: "https://icecast.radiofrance.fr/francemusique-hifi.aac",
    websiteUrl: "https://www.radiofrance.fr/francemusique",
    onlineStreamUrl: "https://www.radiofrance.fr/francemusique",
    shortLabel: {
      en: "Classical and jazz-heavy station for calm, early evenings.",
      fr: "Radio classique et jazz pour les moments calmes.",
      it: "Radio classica e jazz per momenti più tranquilli.",
      uk: "Радіо класики та джазу для спокійного вечора.",
    },
    usefulFor: ["quiet evenings", "families", "seafront evenings"],
  },
  {
    id: "radio-classique",
    image: "/images/guide/radio-classique.png",
    tenant: "menton",
    name: {
      en: "Radio Classique",
      fr: "Radio Classique",
      it: "Radio Classique",
      uk: "Radio Classique",
    },
    fmFrequency: "102.7 MHz",
    contentTypes: ["music", "classical", "business", "news"],
    languages: ["French"],
    musicStyles: ["classical"],
    websiteUrl: "https://www.radioclassique.fr/",
    onlineStreamUrl: "https://www.radioclassique.fr/",
    shortLabel: {
      en: "Classical station with a calm business-oriented tone.",
      fr: "Radio classique avec ton plus posé.",
      it: "Radio classica dal tono elegante e pacato.",
      uk: "Класична станція зі спокійнішою подачею.",
    },
    usefulFor: ["work-day", "quiet evenings", "city breaks"],
  },
  {
    id: "rmc",
    image: "/images/guide/rmc.png",
    tenant: "menton",
    name: {
      en: "RMC",
      fr: "RMC",
      it: "RMC",
      uk: "RMC",
    },
    fmFrequency: "98.5 MHz",
    contentTypes: ["talk", "sport", "news", "entertainment"],
    languages: ["French"],
    audioStreamUrl: "https://audio.bfmtv.com/rmcradio_128.mp3",
    websiteUrl: "https://rmc.bfmtv.com/",
    onlineStreamUrl: "https://rmc.bfmtv.com/",
    shortLabel: {
      en: "Talk-heavy station with traffic context and sports.",
      fr: "Radio d'opinion, sport et infos trafic.",
      it: "Radio con notizie, sport e informazione pratica.",
      uk: "Радіо з новинами, спортом і дискусіями.",
    },
    usefulFor: ["sports nights", "traffic", "news"],
  },
  {
    id: "radio-monte-carlo-italia",
    image: "/images/guide/radio-monte-carlo.png",
    tenant: "menton",
    name: {
      en: "Radio Monte Carlo",
      fr: "Radio Monte Carlo",
      it: "Radio Monte Carlo",
      uk: "Radio Monte Carlo",
    },
    fmFrequency: "106.8 MHz",
    contentTypes: ["music", "italian", "cross-border"],
    languages: ["Italian"],
    musicStyles: ["italian pop", "international pop"],
    websiteUrl: "https://www.radiomontecarlo.it/",
    onlineStreamUrl: "https://www.radiomontecarlo.it/",
    shortLabel: {
      en: "Italian-language music and lifestyle from the border side.",
      fr: "Radio italienne utile pour la transition vers la côte italienne.",
      it: "Radio italiana utile in vicinanza del confine e per giorno in Italia.",
      uk: "Італійська радіостанція для переходів біля кордону.",
    },
    usefulFor: ["italian border", "family", "day trips"],
  },
  {
    id: "nrj-cote-dazur",
    image: "/images/guide/nrj-cote-d-azur.png",
    tenant: "menton",
    name: {
      en: "NRJ Côte d’Azur",
      fr: "NRJ Côte d’Azur",
      it: "NRJ Côte d’Azur",
      uk: "NRJ Côte d’Azur",
    },
    fmFrequency: "99.8 MHz",
    contentTypes: ["music", "hits", "lifestyle"],
    languages: ["French"],
    musicStyles: ["pop", "top 40"],
    websiteUrl: "https://www.nrj.fr/",
    onlineStreamUrl: "https://www.nrj.fr/",
    shortLabel: {
      en: "Mainstream pop music station for beach days.",
      fr: "Musique de têtes d'affiche pour les journées plage.",
      it: "Pop commerciale per giornate in spiaggia.",
      uk: "Поп-станція для пляжного настрою.",
    },
    usefulFor: ["family", "beach days", "easy listening"],
  },
  {
    id: "rtl2-cote-dazur",
    image: "/images/guide/rtl2-cote-d-azur.png",
    tenant: "menton",
    name: {
      en: "RTL2 Côte d’Azur",
      fr: "RTL2 Côte d’Azur",
      it: "RTL2 Côte d’Azur",
      uk: "RTL2 Côte d’Azur",
    },
    fmFrequency: "92.9 MHz",
    contentTypes: ["music", "pop-rock", "drive"],
    languages: ["French"],
    musicStyles: ["pop-rock", "adult contemporary"],
    websiteUrl: "https://www.rtl2.fr/",
    onlineStreamUrl: "https://www.rtl2.fr/",
    shortLabel: {
      en: "Pop and rock for coastal driving and easy evenings.",
      fr: "Pop-rock pour les trajets et les retours de soirée.",
      it: "Pop-rock per la guida e i ritorni serali.",
      uk: "Пісні поп/рок для доріг і повільних вечорів.",
    },
    usefulFor: ["day trips", "driving", "evening drives"],
  },
  {
    id: "nostalgie",
    image: "/images/guide/nostalgie.png",
    tenant: "menton",
    name: {
      en: "Nostalgie",
      fr: "Nostalgie",
      it: "Nostalgie",
      uk: "Nostalgie",
    },
    fmFrequency: "93.5 MHz",
    contentTypes: ["music", "oldies", "classics"],
    languages: ["French"],
    musicStyles: ["oldies", "classic hits"],
    websiteUrl: "https://www.nostalgie.fr/",
    onlineStreamUrl: "https://www.nostalgie.fr/",
    shortLabel: {
      en: "Classic and older pop hits for relaxed family listening.",
      fr: "Classiques et oldies pour une ambiance relax.",
      it: "Classici e oldies per un ascolto rilassato.",
      uk: "Класика та старі хіти для спокійного прослуховування.",
    },
    usefulFor: ["relaxed evening", "family", "quiet drives"],
  },
  {
    id: "europe-2",
    image: "/images/guide/europe-2.png",
    tenant: "menton",
    name: {
      en: "Europe 2",
      fr: "Europe 2",
      it: "Europe 2",
      uk: "Europe 2",
    },
    fmFrequency: "92.1 MHz",
    contentTypes: ["music", "pop", "rock"],
    languages: ["French"],
    musicStyles: ["pop", "rock", "adult pop"],
    websiteUrl: "https://www.europe2.fr/",
    onlineStreamUrl: "https://www.europe2.fr/",
    shortLabel: {
      en: "General pop-rock station for daily commuting and weekends.",
      fr: "Station pop-rock pour trajets quotidiens et week-end.",
      it: "Pop-rock generalista per spostamenti e weekend.",
      uk: "Станція поп-року для щоденних переїздів і вихідних.",
    },
    usefulFor: ["day trips", "beach days", "weekend travel"],
  },
  {
    id: "rfm",
    image: "/images/guide/rfm.png",
    tenant: "menton",
    name: {
      en: "RFM",
      fr: "RFM",
      it: "RFM",
      uk: "RFM",
    },
    fmFrequency: "97.6 MHz",
    contentTypes: ["music", "adult pop", "easy listening"],
    languages: ["French"],
    musicStyles: ["adult contemporary", "popular classics"],
    audioStreamUrl: "https://rfm.lmn.fm/rfm.mp3",
    websiteUrl: "https://www.rfm.fr/",
    onlineStreamUrl: "https://www.rfm.fr/",
    shortLabel: {
      en: "Adult contemporary music in a familiar format.",
      fr: "Pop français et internationale en ton familier.",
      it: "Musica adult contemporary in formato familiare.",
      uk: "Альтернативно знайома поп-музика для відпочинку.",
    },
    usefulFor: ["break mornings", "apartments", "drive home"],
  },
  {
    id: "m-radio",
    image: "/images/guide/m-radio.png",
    tenant: "menton",
    name: {
      en: "M Radio",
      fr: "M Radio",
      it: "M Radio",
      uk: "M Radio",
    },
    audioStreamUrl:
      "https://mfm.ice.infomaniak.ch/mfm-128.mp3?aw_0_1st.playerId=mradio_web&i=26641",
    fmFrequency: "90.3 MHz / 104.1 MHz",
    contentTypes: ["music", "easy listening"],
    languages: ["French"],
    musicStyles: ["French chanson", "French pop"],
    websiteUrl: "https://www.mradio.fr/",
    onlineStreamUrl: "https://www.mradio.fr/",
    shortLabel: {
      en: "French chanson and French-language popular music.",
      fr: "Chanson française et variétés françaises.",
      it: "Canzone francese e pop francese.",
      uk: "Французькі пісні та популярна французька музика.",
    },
    usefulFor: ["french-practice", "quiet evenings", "breakfast plans"],
  },
  {
    id: "melody-dazur",
    image: "/images/guide/melody-d-azur.png",
    tenant: "menton",
    name: {
      en: "Melody d’Azur",
      fr: "Melody d’Azur",
      it: "Melody d’Azur",
      uk: "Melody d’Azur",
    },
    fmFrequency: "100.5 MHz",
    contentTypes: ["music", "variety", "local"],
    languages: ["French"],
    musicStyles: ["variety", "adult pop", "regional"],
    shortLabel: {
      en: "Local-feeling variety station near the Riviera local scene.",
      fr: "Station musicale à ambiance locale en Riviera.",
      it: "Radio locale con impostazione musicale e regionale.",
      uk: "Локальна різноманітна станція із примітною атмосферою.",
    },
    usefulFor: ["slow stays", "local lifestyle", "apartment evenings"],
  },
  {
    id: "agora-cote-dazur",
    image: "/images/guide/agora-cote-d-azur.png",
    tenant: "menton",
    name: {
      en: "Agora Côte d’Azur",
      fr: "Agora Côte d’Azur",
      it: "Agora Côte d’Azur",
      uk: "Agora Côte d’Azur",
    },
    fmFrequency: "88.9 MHz",
    contentTypes: ["community", "local-news", "talk", "music"],
    languages: ["French"],
    musicStyles: ["mixed local programming"],
    shortLabel: {
      en: "Community-style local station for niche local updates.",
      fr: "Radio locale communautaire pour une couverture de proximité.",
      it: "Radio comunitaria locale per aggiornamenti di prossimità.",
      uk: "Місцева громадська станція з новинами близького радіусу.",
    },
    usefulFor: ["local-news", "family outings", "city planning"],
  },
];

export function getRadioStationById(id: string): RadioStation | undefined {
  return radioStations.find((station) => station.id === id);
}

export function getRadioStationsForTenant(region: RadioTenantOrRegion, stationIds?: string[]): RadioStation[] {
  const set = stationIds ? new Set(stationIds) : undefined;

  return radioStations.filter((station) => {
    if (station.tenant !== region) return false;
    if (!set || set.size === 0) return true;
    return set.has(station.id);
  });
}

export function getRadioStationLabel(station: RadioStation, locale: Locale): string {
  return station.name[locale] ?? station.name.en;
}
