import type { Locale } from "@/i18n/locales";

export const navItems = [
  { key: "apartments", href: "/apartments" },
  { key: "guide", href: "/guide" },
  { key: "events", href: "/events" },
  { key: "faq", href: "/faq" },
  { key: "contact", href: "/contact" },
] as const;

export const routeLabels: Record<Locale, Record<string, string>> = {
  en: {
    home: "Home",
    apartments: "Apartments",
    availability: "Check availability",
    guide: "Menton guide",
    events: "Events",
    faq: "FAQ",
    contact: "Contact",
    privacy: "Privacy Policy",
    legal: "Legal Notice",
    cookies: "Cookie Policy",
    bookingTerms: "Booking Terms",
  },
  fr: {
    home: "Accueil",
    apartments: "Appartements",
    availability: "Verifier disponibilite",
    guide: "Guide de Menton",
    events: "Evenements",
    faq: "FAQ",
    contact: "Contact",
    privacy: "Politique de confidentialite",
    legal: "Mentions legales",
    cookies: "Politique cookies",
    bookingTerms: "Conditions de reservation",
  },
  it: {
    home: "Home",
    apartments: "Appartamenti",
    availability: "Controlla disponibilita",
    guide: "Guida di Mentone",
    events: "Eventi",
    faq: "FAQ",
    contact: "Contatti",
    privacy: "Informativa privacy",
    legal: "Note legali",
    cookies: "Politica cookie",
    bookingTerms: "Condizioni di prenotazione",
  },
  uk: {
    home: "Home",
    apartments: "Apartments",
    availability: "Check availability",
    guide: "Menton guide",
    events: "Events",
    faq: "FAQ",
    contact: "Contact",
    privacy: "Privacy Policy",
    legal: "Legal Notice",
    cookies: "Cookie Policy",
    bookingTerms: "Booking Terms",
  },
};
