import type { Locale } from "@/i18n/locales";

export type LocalizedText = Record<Locale, string>;

export type WalkingCategory =
  | "beaches"
  | "old-town"
  | "museums-market"
  | "gardens-nature"
  | "italy-border"
  | "central-essentials"
  | "train-day-trips";

export type WalkingDistanceItem = {
  id: string;
  name: string;
  category: WalkingCategory;
  walkingTime: string;
  direction?: LocalizedText;
  note: LocalizedText;
  address?: string;
  googleMapsUrl?: string;
  sourceStatus: "editorial" | "needs_verification";
};

const t = (en: string, fr: string, it: string, uk: string): LocalizedText => ({ en, fr, it, uk });
const maps = (name: string, addressOrArea = "Menton") => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${name} ${addressOrArea}`)}`;

export const walkingCategoryLabels: Record<WalkingCategory, LocalizedText> = {
  beaches: t("Beaches", "Plages", "Spiagge", "Пляжі"),
  "old-town": t("Old town and viewpoints", "Vieille ville et points de vue", "Centro storico e panorami", "Старе місто та оглядові точки"),
  "museums-market": t("Museums and market", "Musees et marche", "Musei e mercato", "Музеї та ринок"),
  "gardens-nature": t("Gardens and nature", "Jardins et nature", "Giardini e natura", "Сади та природа"),
  "italy-border": t("Italy and border walks", "Italie et marches vers la frontiere", "Italia e passeggiate al confine", "Італія та прогулянки до кордону"),
  "central-essentials": t("Zero-distance central essentials", "Essentiels centraux tout proches", "Essenziali centrali vicinissimi", "Центральні місця поруч"),
  "train-day-trips": t("Train and day trips", "Train et excursions", "Treno e gite", "Потяг і поїздки на день"),
};

export const walkingCategoryNotes: Record<WalkingCategory, LocalizedText> = {
  beaches: t("Easy beach choices from the central seafront reference point.", "Des plages faciles depuis le front de mer central.", "Scelte facili per il mare dal lungomare centrale.", "Зручні пляжі від центральної набережної."),
  "old-town": t("Beautiful but hillier: expect steps and elevation once you leave the promenade.", "Tres beau mais plus pentu: prevoyez marches et denivele depuis la promenade.", "Bello ma piu in salita: aspettati scale e dislivello lasciando il lungomare.", "Гарно, але вище: після набережної будуть сходи й підйоми."),
  "museums-market": t("Useful morning stops and culture ideas; check current museum status before planning around a visit.", "Haltes utiles du matin et idees culture; verifiez l'ouverture des musees avant de planifier.", "Tappe utili al mattino e idee culturali; controlla lo stato dei musei prima di programmare.", "Корисні ранкові зупинки й культурні ідеї; перед плануванням перевірте статус музеїв."),
  "gardens-nature": t("Some gardens are farther or uphill. In hot weather, consider a taxi or current local transport options.", "Certains jardins sont plus loin ou en hauteur. Par forte chaleur, envisagez taxi ou transports locaux actuels.", "Alcuni giardini sono piu lontani o in salita. Con il caldo valuta taxi o trasporti locali aggiornati.", "Деякі сади далі або вище. У спеку розгляньте таксі чи актуальний місцевий транспорт."),
  "italy-border": t("Possible for confident walkers, but the train is usually simpler for Italy.", "Possible pour bons marcheurs, mais le train est souvent plus simple pour l'Italie.", "Possibile per camminatori allenati, ma il treno e di solito piu semplice per l'Italia.", "Можливо для впевнених пішоходів, але до Італії зазвичай простіше поїздом."),
  "central-essentials": t("Daily errands, drinks and local information close to the seafront.", "Courses du quotidien, verres et informations locales pres du front de mer.", "Piccole necessita, drink e informazioni locali vicino al lungomare.", "Щоденні справи, напої та локальна інформація поруч із набережною."),
  "train-day-trips": t("The station makes Monaco, Nice and Ventimiglia practical without a car. Check current schedules.", "La gare rend Monaco, Nice et Vintimille pratiques sans voiture. Verifiez les horaires actuels.", "La stazione rende Monaco, Nizza e Ventimiglia pratiche senza auto. Controlla gli orari aggiornati.", "Вокзал робить Монако, Ніццу й Вентімілью зручними без авто. Перевіряйте актуальний розклад."),
};

export const walkingDistanceItems: WalkingDistanceItem[] = [
  { id: "plage-sablettes", name: "Plage des Sablettes", category: "beaches", walkingTime: "3-5 min", note: t("Main beach area near the old town and seafront.", "Plage principale pres de la vieille ville et du front de mer.", "Zona balneare principale vicino al centro storico e al lungomare.", "Головна пляжна зона біля старого міста та набережної."), googleMapsUrl: maps("Plage des Sablettes", "Menton"), sourceStatus: "editorial" },
  { id: "plage-casino", name: "Plage du Casino", category: "beaches", walkingTime: "2-3 min", note: t("Next to Casino Barrière and the central promenade.", "A cote du Casino Barriere et de la promenade centrale.", "Accanto al Casino Barrière e al lungomare centrale.", "Поруч із Casino Barrière та центральною набережною."), googleMapsUrl: maps("Plage du Casino", "Menton"), sourceStatus: "editorial" },
  { id: "plage-fossan", name: "Plage du Fossan", category: "beaches", walkingTime: "8-10 min", direction: t("east", "est", "est", "на схід"), note: t("Along the seafront.", "Le long du front de mer.", "Lungo il lungomare.", "Уздовж набережної."), googleMapsUrl: maps("Plage du Fossan", "Menton"), sourceStatus: "editorial" },
  { id: "plage-garavan", name: "Plage de Garavan", category: "beaches", walkingTime: "15-20 min", direction: t("east", "est", "est", "на схід"), note: t("Toward Garavan port.", "Vers le port de Garavan.", "Verso il porto di Garavan.", "У напрямку порту Garavan."), googleMapsUrl: maps("Plage de Garavan", "Menton"), sourceStatus: "editorial" },
  { id: "borrigo-beaches", name: "Borrigo beaches", category: "beaches", walkingTime: "10-12 min", direction: t("west", "ouest", "ovest", "на захід"), note: t("Along Promenade du Soleil.", "Le long de la Promenade du Soleil.", "Lungo Promenade du Soleil.", "Уздовж Promenade du Soleil."), googleMapsUrl: maps("Borrigo beaches", "Menton"), sourceStatus: "editorial" },
  { id: "promenade-du-soleil", name: "Promenade du Soleil", category: "old-town", walkingTime: "0 min", note: t("You are already on the seafront orientation line.", "Vous etes deja sur l'axe du front de mer.", "Sei gia sulla linea di orientamento del lungomare.", "Ви вже на головній лінії орієнтації вздовж моря."), googleMapsUrl: maps("Promenade du Soleil", "Menton"), sourceStatus: "editorial" },
  { id: "rue-saint-michel", name: "Rue Saint-Michel", category: "old-town", walkingTime: "5 min", note: t("Old-town shopping and restaurant street.", "Rue de commerces et restaurants de la vieille ville.", "Via di negozi e ristoranti del centro storico.", "Вулиця старого міста з магазинами й ресторанами."), googleMapsUrl: maps("Rue Saint-Michel", "Menton"), sourceStatus: "editorial" },
  { id: "rampes-saint-michel", name: "Les Rampes Saint-Michel", category: "old-town", walkingTime: "7-8 min", note: t("Stairs and views toward the basilica.", "Marches et vues vers la basilique.", "Scale e viste verso la basilica.", "Сходи й краєвиди в напрямку базиліки."), googleMapsUrl: maps("Les Rampes Saint-Michel", "Menton"), sourceStatus: "editorial" },
  { id: "basilique-saint-michel", name: "Basilique Saint-Michel-Archange", category: "old-town", walkingTime: "12-15 min", note: t("Uphill through the old town.", "Montee par la vieille ville.", "In salita attraverso il centro storico.", "Підйом через старе місто."), googleMapsUrl: maps("Basilique Saint-Michel-Archange", "Menton"), sourceStatus: "editorial" },
  { id: "cimetiere-vieux-chateau", name: "Cimetière du Vieux Château", category: "old-town", walkingTime: "15-18 min", note: t("Panoramic viewpoint; uphill.", "Point de vue panoramique; en montee.", "Punto panoramico; in salita.", "Панорамна точка; підйом угору."), googleMapsUrl: maps("Cimetière du Vieux Château", "Menton"), sourceStatus: "editorial" },
  { id: "chapelle-penitents-noirs", name: "Chapelle des Pénitents Noirs", category: "old-town", walkingTime: "10-12 min", note: t("On the route toward the basilica.", "Sur le chemin vers la basilique.", "Sul percorso verso la basilica.", "На маршруті до базиліки."), googleMapsUrl: maps("Chapelle des Pénitents Noirs", "Menton"), sourceStatus: "editorial" },
  { id: "musee-bastion", name: "Musée Jean Cocteau — Le Bastion", category: "museums-market", walkingTime: "7-8 min", note: t("By the old port and Bastion area.", "Pres du vieux port et du Bastion.", "Presso il vecchio porto e il Bastion.", "Біля старого порту та району Bastion."), googleMapsUrl: maps("Musée Jean Cocteau Le Bastion", "Menton"), sourceStatus: "needs_verification" },
  { id: "musee-wunderman", name: "Musée Jean Cocteau — Collection Wunderman", category: "museums-market", walkingTime: "6-7 min", note: t("Near Halles market; verify current status and opening before visiting.", "Pres des Halles; verifiez le statut et l'ouverture avant la visite.", "Vicino alle Halles; verifica stato e apertura prima della visita.", "Біля ринку Halles; перед візитом перевірте поточний статус і відкриття."), googleMapsUrl: maps("Musée Jean Cocteau Collection Wunderman", "Menton"), sourceStatus: "needs_verification" },
  { id: "marche-halles", name: "Marché des Halles", category: "museums-market", walkingTime: "6-7 min", address: "5 Quai de Monléon", note: t("Morning market; check current hours.", "Marche du matin; verifiez les horaires actuels.", "Mercato mattutino; controlla gli orari aggiornati.", "Ранковий ринок; перевірте актуальні години."), googleMapsUrl: maps("Marché des Halles", "5 Quai de Monléon Menton"), sourceStatus: "needs_verification" },
  { id: "palais-europe", name: "Palais de l’Europe / Tourist Office", category: "museums-market", walkingTime: "4-5 min", address: "8 Avenue Boyer", note: t("Useful for local information.", "Utile pour les informations locales.", "Utile per informazioni locali.", "Корисно для локальної інформації."), googleMapsUrl: maps("Palais de l’Europe", "8 Avenue Boyer Menton"), sourceStatus: "editorial" },
  { id: "serre-madone", name: "Jardin Serre de la Madone", category: "gardens-nature", walkingTime: "40-45 min", note: t("Around 3.6 km from the centre; not the easiest walk for most guests. Consider current local bus options or a taxi.", "Environ 3,6 km du centre; pas la marche la plus facile pour la plupart des voyageurs. Envisagez bus local actuel ou taxi.", "Circa 3,6 km dal centro; non e la camminata piu facile per molti ospiti. Valuta bus locali aggiornati o taxi.", "Близько 3,6 км від центру; для більшості гостей це не найпростіша прогулянка. Розгляньте актуальні місцеві автобуси або таксі."), googleMapsUrl: maps("Jardin Serre de la Madone", "Menton"), sourceStatus: "needs_verification" },
  { id: "val-rahmeh", name: "Jardin Botanique Val Rahmeh", category: "gardens-nature", walkingTime: "20-25 min", note: t("Closer from the Garavan side; check current opening hours.", "Plus proche cote Garavan; verifiez les horaires actuels.", "Piu vicino dal lato Garavan; controlla gli orari aggiornati.", "Ближче з боку Garavan; перевірте актуальні години роботи."), googleMapsUrl: maps("Jardin Botanique Val Rahmeh", "Menton"), sourceStatus: "needs_verification" },
  { id: "jardins-bioves", name: "Jardins Biovès", category: "gardens-nature", walkingTime: "5-7 min", note: t("Central gardens near the seafront; important during the Lemon Festival.", "Jardins centraux pres du front de mer; importants pendant la Fete du Citron.", "Giardini centrali vicino al lungomare; importanti durante la Festa del Limone.", "Центральні сади біля набережної; важливі під час Фестивалю лимонів."), googleMapsUrl: maps("Jardins Biovès", "Menton"), sourceStatus: "editorial" },
  { id: "italian-border", name: "French/Italian border walk", category: "italy-border", walkingTime: "40-60 min", note: t("Possible for confident walkers along the coast, depending on exact route.", "Possible pour bons marcheurs le long de la cote, selon le trajet exact.", "Possibile per camminatori sicuri lungo la costa, secondo il percorso scelto.", "Можливо для впевнених пішоходів уздовж узбережжя, залежно від маршруту."), googleMapsUrl: maps("French Italian border", "Menton"), sourceStatus: "editorial" },
  { id: "ventimiglia-centre", name: "Ventimiglia centre", category: "italy-border", walkingTime: "60-90 min", note: t("About 5-6 km; better by train for most guests.", "Environ 5-6 km; le train est preferable pour la plupart des voyageurs.", "Circa 5-6 km; meglio il treno per la maggior parte degli ospiti.", "Близько 5-6 км; для більшості гостей краще їхати потягом."), googleMapsUrl: maps("Ventimiglia centre", "Italy"), sourceStatus: "editorial" },
  { id: "biera-daqui", name: "Biera d’Aquì", category: "central-essentials", walkingTime: "1-2 min", note: t("Verify exact branch and hours before visiting.", "Verifiez l'adresse exacte et les horaires avant la visite.", "Verifica sede esatta e orari prima della visita.", "Перед візитом перевірте точну адресу та години."), googleMapsUrl: maps("Biera d’Aquì", "Menton"), sourceStatus: "needs_verification" },
  { id: "inky-bar-sablettes", name: "Inky Bar / Sablettes", category: "central-essentials", walkingTime: "around 3 min", note: t("From the Sablettes side; verify exact route from your apartment.", "Depuis le cote Sablettes; verifiez le trajet exact depuis l'appartement.", "Dal lato Sablettes; verifica il percorso esatto dall'appartamento.", "З боку Sablettes; перевірте точний маршрут від апартаментів."), googleMapsUrl: maps("Inky Bar Sablettes", "Menton"), sourceStatus: "needs_verification" },
  { id: "casino-barriere", name: "Casino Barrière Menton", category: "central-essentials", walkingTime: "0 min", note: t("Central seafront reference point.", "Point de reference central du front de mer.", "Punto di riferimento centrale sul lungomare.", "Центральна точка орієнтації на набережній."), googleMapsUrl: maps("Casino Barrière Menton", "Menton"), sourceStatus: "editorial" },
  { id: "tourist-office", name: "Tourist Office / Palais de l’Europe", category: "central-essentials", walkingTime: "4-5 min", note: t("Useful for current local information.", "Utile pour les informations locales actuelles.", "Utile per informazioni locali aggiornate.", "Корисно для актуальної локальної інформації."), address: "8 Avenue Boyer", googleMapsUrl: maps("Palais de l’Europe", "8 Avenue Boyer Menton"), sourceStatus: "editorial" },
  { id: "gare-menton", name: "Gare de Menton", category: "central-essentials", walkingTime: "8-10 min", note: t("Useful for Monaco, Nice and Ventimiglia day trips.", "Utile pour Monaco, Nice et Vintimille.", "Utile per Monaco, Nizza e Ventimiglia.", "Зручно для поїздок до Монако, Ніцци й Вентімільї."), googleMapsUrl: maps("Gare de Menton", "Menton"), sourceStatus: "editorial" },
  { id: "monaco-train", name: "Monaco by train", category: "train-day-trips", walkingTime: "8-10 min to station", note: t("Reach Gare de Menton on foot, then check current train schedules before travelling.", "Rejoignez la gare a pied, puis verifiez les horaires de train avant de partir.", "Raggiungi la stazione a piedi, poi controlla gli orari dei treni.", "Дійдіть до вокзалу пішки, а перед поїздкою перевірте актуальний розклад."), googleMapsUrl: maps("Gare de Menton", "Menton"), sourceStatus: "needs_verification" },
  { id: "nice-train", name: "Nice by train", category: "train-day-trips", walkingTime: "8-10 min to station", note: t("Train times vary by day and season. Check current schedules.", "Les horaires varient selon le jour et la saison. Verifiez les horaires actuels.", "Gli orari variano per giorno e stagione. Controlla gli orari aggiornati.", "Розклад залежить від дня й сезону. Перевіряйте актуальний графік."), googleMapsUrl: maps("Gare de Menton", "Menton"), sourceStatus: "needs_verification" },
  { id: "ventimiglia-train", name: "Ventimiglia by train", category: "train-day-trips", walkingTime: "8-10 min to station", note: t("Usually simpler than walking to Italy for most visitors.", "Souvent plus simple que marcher jusqu'en Italie pour la plupart des visiteurs.", "Di solito piu semplice che camminare fino in Italia.", "Для більшості гостей зазвичай простіше, ніж іти до Італії пішки."), googleMapsUrl: maps("Gare de Menton", "Menton"), sourceStatus: "needs_verification" },
];

export const walkingCategoryOrder: WalkingCategory[] = ["beaches", "old-town", "museums-market", "gardens-nature", "italy-border", "central-essentials", "train-day-trips"];
